#!/usr/bin/env python3
#
# Cross Platform and Multi Architecture Advanced Binary Emulation Framework
#

import os

from typing import Optional

import sys
sys.path.append("../../..")

from qiling.core import Qiling
from qiling.const import QL_ARCH, QL_OS, QL_VERBOSE

from qiling.extensions.afl import ql_afl_fuzz_custom
from qiling.arch.models import ARM_CPU_MODEL
from cortex_M3_profile import cortexm3
from unicorn import UC_ERR_OK
from unicorn.arm_const import *
from qiling.extensions.coverage import utils as cov_utils
import importlib.util
import os
from unicorn import UcError


class MemoryMapper:

      def __init__(self, mapPath:str=None):
            self.mapPath = mapPath 
            self._map = None

      @property
      def map(self):
            return self._map

      def setMap(self):
            if not self.mapPath.endswith(".py"):
                  raise ValueError("Must be a .py file")

            spec = importlib.util.spec_from_file_location("dynamic_module", self.mapPath)
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)

            for attr_name in dir(module):
                  if attr_name.startswith("__"):  
                        continue
                  attr = getattr(module, attr_name)
                  if isinstance(attr, dict):
                        self._map = attr
                        return

            raise ValueError("No dictionary found in the module")


      def fix(self, ql, access, addr, size, value):
            print(hex(addr))
            print(size)
            if size <1024: 
                  ql.mem.map(addr//1024*1024, 1024,info="ram")
            else :
                  ql.mem.map(addr//1024*1024, size,info="ram")
            return 


      def mapTheMap(self, ql):
            if self._map is not None: 
                  for start in self._map:
                        # for the moment we round the address, to the nearest page size do we want to be more precise ?
                        try :
                              size = self._map[start]["size"] 
                              if self._map[start]["size"]<1024: 
                                    size = 1024
                              # I think I've added the ram info for the snapshot
                              print(hex(start//1024*1024))
                              print(hex(size//1024*1024))
                              ql.mem.map(start//1024*1024,size//1024*1024,info="ram")
                        except MemoryError as e :
                              raise
            else: 
                  raise AttributeError("Map unitialized")


def main(input_file: str):
    
    # we use a global variable to hold one input 
    global fuzzing_input
    fuzzing_input = bytes()

    def provide_TC_bit(ql:Qiling): 
        print("[+] Provided the TC bit")
        ql.mem.write(0x40013800, b"\x40\x00\x00\x00")

    def provide_RXNE_bit(ql:Qiling): 
        print("[+] Provided the RXNE bit")
        ql.mem.write(0x40013800, b"\x20\x00\x00\x00")
    
    def provide_DR_byte(ql:Qiling): 
        #Here we just skip the entire polling logic function
        print("[+] Provided the DR byte")
        global fuzzing_input
        # Consume one byte at a time of the generated input
        if len(fuzzing_input)>0: 
            ql.mem.write(0x40013804,fuzzing_input[:1])
            fuzzing_input = fuzzing_input[1:]
        else:
            # we consumed all the values
            ql.arch.regs.arch_pc = 0x1ffff3fb

    # setup the emulation
    ql = Qiling(["./firmware.bin", 0x0], archtype=QL_ARCH.CORTEX_M, ostype=QL_OS.MCU, verbose=QL_VERBOSE.DISABLED, cputype=ARM_CPU_MODEL.ARM_CORTEX_M3, env=cortexm3)

    #Using the snapshot
    ql.restore(snapshot="./execution.bin")    

    mapper = MemoryMapper()
    ql.hook_mem_unmapped(mapper.fix)
    # we rewrite the code at another place in memory : this is a particularity of the firmware 
    with open("./firmware.bin", "rb") as f :
        code = f.read()
    ql.mem.write(0x1FFFF000, code)

    # setup all the hooks
    ql.hook_address(provide_TC_bit,0x1ffff02e)
    ql.hook_address(provide_RXNE_bit,0x1ffff1ee)
    ql.hook_address(provide_DR_byte,0x1ffff1f6)


    # this is called each time a new input is generated, we assign this value to the global variable
    def place_input_callback(ql: Qiling, input_bytes: bytes, persistent_round: int) -> Optional[bool]:
        """Called with every newly generated input."""
        global fuzzing_input
        fuzzing_input = input_bytes

        return True

    def fuzzing_callback(ql: Qiling):
        #this is executed each time a new process is generated by the forkserver       
        try:
            ql.run(begin=0x1ffff3fd, end=0x1ffff3fb)
        except UcError as err:
            return err.errno

        return UC_ERR_OK


    def validate_crash_callback(ql: Qiling, result: int, input_bytes: bytes, round: int) -> bool:
        """Validate if a crash is real (basic version)."""
        if result ==UC_ERR_OK: 
            return False

        return True 
    
    #main is only executed one time, which is what we want
    ql_afl_fuzz_custom(
            ql,
            input_file,
            place_input_callback,
            fuzzing_callback=fuzzing_callback,
            validate_crash_callback=validate_crash_callback,
            always_validate=True,
            exits=[0x1ffff3fb]
        )

    os.exit(0)

if __name__ == "__main__":
    if len(sys.argv) == 1:
        raise ValueError("No input file provided.")

    main(sys.argv[1])